package:
  name: pgv
  version: 0.0

source:
  path: ../.

build:
  entry_points:
    - pgv = pgv.PGV:pgv

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - biopython
    - alignment
    - matplotlib
    - configparser

test:

about:
